<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net472</TargetFramework>
        <!--<TargetFramework>netstandard2.1</TargetFramework>-->
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <AssemblyTitle>PostPatcher</AssemblyTitle>
        <Product>PostPatcher</Product>
        <Copyright>Copyright © 2026</Copyright>
        <OutputPath>bin/$(Configuration)/</OutputPath>
        <LangVersion>latest</LangVersion>
        <DisableImplicitFrameworkReferences>true</DisableImplicitFrameworkReferences>
        <FrameworkPathOverride>$(MSBuildProjectDirectory)/../Vanilla</FrameworkPathOverride>
    </PropertyGroup>

    <PropertyGroup>
        <DebugType Condition=" '$(Configuration)' == 'Debug' ">full</DebugType>
        <DebugType Condition=" '$(Configuration)' == 'Release' ">pdbonly</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <TargetDirFiles Include="$(TargetDir)/**" />
    </ItemGroup>
    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
        <MakeDir Directories="$(ProjectDir)Output" />
        <Copy SourceFiles="@(TargetDirFiles)" DestinationFolder="$(ProjectDir)Output" />
    </Target>

    <ItemGroup>
        <PackageReference Include="Mono.Cecil" Version="0.11.3">
            <IncludeAssets>all</IncludeAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <Reference Include="../Vanilla/Assembly-CSharp.dll"/>
        <Reference Include="../Vanilla/TeamCherry.*.dll"/>
        <Reference Include="../Vanilla/mscorlib.dll"/>
        <Reference Include="../Vanilla/netstandard.dll"/>
        <Reference Include="../Vanilla/Newtonsoft.Json.dll"/>
        <Reference Include="../Vanilla/PlayMaker.dll"/>
        <Reference Include="../Vanilla/UnityEngine.dll"/>
        <Reference Include="../Vanilla/UnityEngine.*.dll"/>

        <Reference Include="../Vanilla/Unity.*.dll"/>
        <Reference Include="../Vanilla/Mono.*.dll"/>
        <Reference Include="../Vanilla/System.dll"/>
        <Reference Include="../Vanilla/System.*.dll"/>
    </ItemGroup>
</Project>
