name: docs

on:
  push:
    branches: [ master, docs ]

jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout `docs` branch
        uses: actions/checkout@v4
        with:
          ref: docs
          path: docs
      - name: Build docs
        uses: nunit/docfx-action@v3.4.2
        with:
          args: docs/docfx.json
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: DocFX
          force_orphan: true
