name: docs

on:
  push:
    branches: [ master, docs ]

jobs:
  docfx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Checkout `docs` branch
        uses: actions/checkout@v4
        with:
          ref: docs
          path: docs
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 6.0.x
      - name: Setup MSBuild
        run: |
          sudo apt-get update -y
          sudo apt-get install -y mono-devel mono-xbuild
      - name: Download DocFX
        working-directory: docs
        run: |
          wget https://github.com/dotnet/docfx/releases/download/v2.59.4/docfx.zip -O docfx.zip
          unzip docfx.zip -d docfx
      - name: Build Documentation
        working-directory: docs
        run: |
          mono docfx/docfx.exe 
      - name: Publish
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: DocFX
          force_orphan: true
